### ISSUE TITLE
Create release for LIGO ER9

### ISSUE THREAD

**Issue by lpsinger** [farr/skyarea#32]
Hey Will. Would you please tag a release for ER9? I'm thinking of packaging this up as a deb and an rpm so that it gets installed cluster-wide. I see that you have set the version of the package to 1.0, but I suggest being much more conservative and starting with 0.1. So I'd suggest setting `version='0.1'` in `setup.py` and then creating a `v0.1` release tag on GitHub. I can take care of the rest.

**Comment by farr** [comment]
Done.  There should now be a v0.1 tag that you can use.
