### ISSUE TITLE
How to calculate bic when points are dropped due to degenerate clusters?

### ISSUE THREAD

**Issue by lpsinger** [farr/skyarea#71]
When we search over the number of clusters _k_ over _n_ points with dimensionality _d_, it often occurs that there are degenerate clusters that contain fewer than _d_ distinct points. When this happens, we have to discard the degenerate clusters. What is the correct way to count degenerate clusters in the BIC? Should the discarded points be counted in the numerator? Should the discarded degrees of freedom be counted in the denominator? Right now, we are counting both.

**Comment by farr** [comment]
I think it is appropriate to count both: you are still fitting a model with that number of degrees of freedom to that amount of data.  The fact that those degrees of freedom turn out to be "dropped" (or, in stats language, "not identified") doesn't change the fact that you have them at your disposal to make the fit better if you can; the fact that those data points don't contribute to the final distribution doesn't mean that they *couldn't* have been informative in principle.

Does that make sense?

**Comment by lpsinger** [comment]
Good enough for me!
