### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by vitale82** [farr/skyarea#8]
Hi Will,

I'm just new of github, thus I'm not sure how everything works. In particular I'm not sure I can push myself to the repo. Thus for the moment I'm just opening a ticket.

Working with the latest version of the code  I do see occasional errors like:

``` python
Traceback (most recent call last):
  File "/home/salvatore.vitale/lalsuites/skyPP/bin/run_sky_area.py", line 150, in <module>
    inj.simulation_id, inj.longitude, inj.latitude)
  File "/home/salvatore.vitale/lalsuites/skyPP/bin/run_sky_area.py", line 58, in save_areas
    areas = skypost.sky_area(levels)
  File "/home/salvatore.vitale/lalsuites/skyPP/sky_area/sky_area_clustering.py", line 510, in sky_area
    post_levels = [self.greedy_posteriors[int(round(cl*self.ranking_pts.shape[0]))] for cl in cls]
IndexError: index out of bounds
```

Something else (minor):

1) The code fails to read sim_inspiral table since load_finename is not give a ContentHandler. I can easily push a fix for this, if I have the rights.
2) That may just be me not setting the env variables properly, but the following fails for me (in run_sky_area.py)

import sky_area.sky_area_clustering as sac

I had to change it in 

import sky_area_clustering as sac

Cheers,
salvo

**Comment by lpsinger** [comment]
Seems to be fixed on master now, right? @vitale82, may we close this now?
